#!/usr/bin/env bash
#
# Check if domain is free or not.
#
if [ "$#" == "0" ]; then
    echo "usage: domain <name.tld>"
    exit 1
fi
#
whois $1 | egrep -q \
    '^No match|^NOT FOUND|not found|^Not fo|AVAILABLE|^No Data Fou|has not been regi|No entri'
#
if [ $? -eq 0 ]; then
    echo "ok : $1"
else
    echo "no : $1"
fi
#
