#!/usr/bin/env bash
#
# Show a summary of changes, eg: 'git changes 2 src' shows two days of changes
# in the 'src' directory.
#
re='^[0-9]+'
if [[ $1 =~ $re ]]
then
    days=${1}
    shift
else
    days='1'
fi
git shortlog \
    --invert-grep --author="Bot" \
    --since=$days.days "$@"
