#!/usr/bin/env bash

cur=$PWD

for d in *
do
    cd "$d" || return
    status=$(unbuffer git status -sb | tr -d '#')
    printf "%-30s:: %s\\n" "${d}" "${status}"
    cd "${cur}" || return
done

cd "${cur}" || exit 1
exit 0
