#!/usr/bin/env bash

cur=$PWD

for d in *
do
    if [[ -d "$d" ]]
    then
        cd "$d" || return
        status=$(2>/dev/null unbuffer git status -sb | tr -d '#')
        printf "%-30s:: %s\\n" "${d}" "${status}"
        cd "${cur}" || return
    fi
done

cd "${cur}" || exit 1
exit 0
