#!/usr/bin/env bash

bsima_cert=/tmp/bsima.me.cert

openssl s_client -connect bsima.me:6697 < /dev/null 2>/dev/null | \
    openssl x509 > $bsima_cert

case "$1" in
    cert) openssl x509 -in $bsima_cert -fingerprint -sha256 -noout
    ;;
    pubkey) openssl x509 -in $bsima_cert -pubkey -noout | \
            openssl pkey -pubin -outform der | \
            openssl dgst -sha256 -c | \
            tr a-z A-Z
    ;;
    *) echo "usage: $(basename $0) {cert,pubkey}"; exit 1
    ;;
esac


