#!/usr/bin/env bash

# FIXME: replace ~/me with ~/docs

cur=$PWD

function usage { 
    echo "Usage: $0 [status]" 1>&2
    exit 1
}

function allStatuses {
    for d in ~/.password-store ~/bin ~/config ~/org ~/web ~/me
    do
        cd "${d}"
    
        dirname=${d/\/home\/ben/\~}
        status=$(unbuffer git status -sb | tr -d '#')
        printf "%-20s:: %s\n" "${dirname}" "${status}"
    done
    exit 0
}

while true; do
    case "$1" in
        status) allStatuses ;;
        *) usage ;;
    esac
done

cd "${cur}"
