#!/usr/bin/env sh

set -o errexit
set -o nounset
#set -o xtrace

REQ=$(curl -sS freegeoip.net/json/)
LAT=$(echo $REQ | jq ".latitude")
LON=$(echo $REQ | jq ."longitude")

# start redshift as a background task
redshift -l $LAT:$LON &
