#!/usr/bin/env python3.5

import argparse
from readability import Document
import requests
import sys

cli = argparse.ArgumentParser('read a url')
cli.add_argument('url', type=str)

if __name__ == '__main__':
    try:
        args = cli.parse_args()
        resp = requests.get(args.url)
        doc = Document(resp.text)
        sys.stdout.write(doc.summary())
        sys.exit(0)
    except:
        sys.exit(1)
